### ISSUE TITLE
Updating contact creates a new contact instead of updating 

### ISSUE THREAD

**Issue by DylanVerstraete** [threefoldfoundation/tfchain-wallet-electron#150]
```
    const { account } = this.props
    const { address_book: addressBook } = account
    try {
      addressBook.contact_update(contactName, { name: contactName, recipient: contactAddress })
```

**Comment by GlenDC** [comment]
This should not create a new contact, can you list me your contacts prior to this call, and can you share the `contactAddress` and `contactName` when this happened?

Will add a unit test extra for it.

**Comment by GlenDC** [comment]
Don't think there was ever an issue in the code. Did change it a bit by storing it as a list instead of a dict, so we can fetch and check using the base-sensitivity name comparisons.

Added a unit test as well to ensure I can update an existing contact.

When you give the recipient in the opts parameter it will indeed create a new contact object under the hood. However, as long as you give the same name (in the opts param) as the name you specify the regular name parameter (as you do in your example), you'll be able to fetch the contact using the same name as you were used too.

The `contact_update` function also returns the contact object created and available for the specified name.

Still, I don't get what issue you really have here. As long as you do not try to store contact objects yourself (for more than just a direct usage within a props-flow), you should be good. Because if you do store objects for a longer time, and you update that contact while still having the object stored that used to represent the contact, then there will be indeed a disconnect between the 2.
